using System;
using System.Collections.Generic;
using System.Linq;
using FluentValidation.Results;
using ReventInject;

namespace RubyReloaded.AuthService.Application.Common.Exceptions
{
    public class ValidationException : Exception
    {
        public ValidationException()
            : base("One or more validation failures have occurred.")
        {
            Errors = new Dictionary<string, string[]>();
        }

        public ValidationException(IEnumerable<ValidationFailure> failures)
            : this()
        {
            var failureGroups = failures
                .GroupBy(e => e.PropertyName, e => e.ErrorMessage);

            foreach (var failureGroup in failureGroups)
            {
                var propertyName = failureGroup.Key;
                var propertyFailures = failureGroup.ToArray();

                Errors.Add(propertyName, propertyFailures);
            }
        }

        public IDictionary<string, string[]> Errors { get; }

        public string GetErrors()
        {
            string errors = null;
            try
            {
                if (Errors?.Count() > 0)
                {
                    foreach (var error in Errors)
                    {
                        errors += error.Value.ToStringItems() + "; ";
                    }
                }
                return errors.TrimEnd(';');
            }
            catch (Exception ex) { return errors; }
        }
    }
}